# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# development:
#   adapter : postgresql
#   host: localhost
#   database: sudokudb
#   user: ubuntu
#   password: ubuntu

development:
  host: ec2-107-21-100-118.compute-1.amazonaws.com
  database: d1mosici8mhtde
  user: mjfygdeywprsod
  password: m7mPCi_y2xGXflbPZL-V-H7IXO