# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# development:
#   adapter : postgresql
#   host: localhost
#   database: sudokudb
#   user: ubuntu
#   password: ubuntu

development:
  host: ec2-23-23-81-171.compute-1.amazonaws.com
  database: dfgijukch9am0t
  user: yzldgxqhwxtiyp
  password: kOnWdEvZhAyVxs5Es0KGFsy7OT